provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  json-uploader:
    lang: go
    handler: ./json-uploader
    image: viveksyngh/json-uploader:latest
  minio-webhook-hanlder:
    lang: go
    handler: ./minio-webhook-hanlder
    image: viveksyngh/minio-webhook-hanlder:latest
